apiVersion: apps/v1
kind: Deployment
metadata:
  name: studycafe
  labels:
    app: studycafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studycafe
  template:
    metadata:
      labels:
        app: studycafe
    spec:
      containers:
        - name: studycafe
          image: username/studycafe:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5